import { Heart, Leaf, PencilRuler, Sparkles } from "lucide-react";

const values = [
  { title: "Useful by nature", text: "We look for pieces that feel good to use and hold up to real, everyday life.", icon: PencilRuler },
  { title: "Room for expression", text: "There is no one right way to make a mark. We make space for every kind of creative practice.", icon: Sparkles },
  { title: "Thoughtful choices", text: "From your desk to the way an order is packed, care belongs in the small things.", icon: Heart },
];

function About() {
  return (
    <>
      <section className="bg-[#FFE9EC]"><div className="mx-auto grid max-w-7xl items-center gap-8 px-5 py-12 sm:px-8 sm:py-16 md:grid-cols-[1fr_0.85fr] lg:px-10 lg:py-20"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#7E000C]">A little about us</p><h1 className="mt-3 font-display text-4xl leading-tight text-[#7E000C] sm:text-5xl">For the love of putting pen to paper.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-stone-700 sm:text-base">Artistry Avenue began with a simple belief: the tools we reach for every day can make ordinary moments feel more considered, more personal, and more full of possibility.</p></div><img src="https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=1100&q=85" alt="Open notebook and writing tools arranged on a desk" className="aspect-[5/4] w-full rounded-md object-cover" /></div></section>
      <section className="mx-auto grid max-w-7xl gap-9 px-5 py-14 sm:px-8 sm:py-18 md:grid-cols-2 md:gap-16 lg:px-10 lg:py-20"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#7E000C]">Our story</p><h2 className="mt-3 font-display text-3xl text-stone-900 sm:text-4xl">A good page changes the pace.</h2></div><div className="space-y-4 text-sm leading-7 text-stone-600 sm:text-base"><p>We wanted a place where a notebook could be more than a notebook, and a pen could invite a thought to stay a little longer. So we started gathering the everyday essentials we loved using ourselves.</p><p>Today, Artistry Avenue is a considered collection of stationery and creative supplies for lists, letters, sketchbooks, big plans, and all the small starts in between.</p></div></section>
      <section className="border-y border-rose-100 bg-[#fffafa]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 sm:px-8 sm:py-16 md:grid-cols-[0.8fr_1.2fr] md:gap-16 lg:px-10"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#7E000C]">What we believe</p><h2 className="mt-3 font-display text-3xl text-stone-900 sm:text-4xl">Our mission</h2></div><p className="font-display text-2xl leading-snug text-[#7E000C] sm:text-3xl">To bring more intention, delight, and possibility to the everyday act of creating.</p></div></section>
      <section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-18 lg:px-10 lg:py-20"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#7E000C]">The things we stand for</p><h2 className="mt-3 font-display text-3xl text-stone-900 sm:text-4xl">Our values, in practice</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{values.map(({ title, text, icon: Icon }) => <article key={title} className="border-t border-rose-200 py-5"><Icon size={23} className="text-[#7E000C]" strokeWidth={1.7} /><h3 className="mt-4 text-base font-semibold text-stone-900">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{text}</p></article>)}</div></section>
      <section className="bg-[#7E000C] text-white"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-12 sm:px-8 sm:py-16 md:grid-cols-[0.8fr_1.2fr] md:items-center lg:px-10"><div><Leaf size={24} className="text-rose-200" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.18em] text-rose-200">Why shop with us</p><h2 className="mt-3 font-display text-3xl sm:text-4xl">Small details. A more thoughtful desk.</h2></div><ul className="space-y-4 text-sm leading-6 text-white/80 sm:text-base"><li className="border-b border-white/20 pb-4">A curated range, chosen for feel, function, and a little spark.</li><li className="border-b border-white/20 pb-4">Clear product details to help you choose with confidence.</li><li>Careful packing and a real appreciation for the people creating with us.</li></ul></div></section>
    </>
  );
}

export default About;